/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResearcherRouteImport } from './routes/researcher'
import { Route as UserRouteImport } from './routes/user'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ResearcherIndexRouteImport } from './routes/researcher.index'
import { Route as ResearcherDiscoverRouteImport } from './routes/researcher.discover'
import { Route as ResearcherExpeditionsRouteImport } from './routes/researcher.expeditions'
import { Route as ResearcherResearchRouteImport } from './routes/researcher.research'
import { Route as ResearcherSavedRouteImport } from './routes/researcher.saved'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as UserAssistantRouteImport } from './routes/user.assistant'
import { Route as UserExpeditionsRouteImport } from './routes/user.expeditions'
import { Route as UserMediaRouteImport } from './routes/user.media'
import { Route as UserRepositoryRouteImport } from './routes/user.repository'
import { Route as UserSavedRouteImport } from './routes/user.saved'
import { Route as UserTimelineRouteImport } from './routes/user.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearcherRoute = ResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ResearcherIndexRoute = ResearcherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearcherRoute,
} as any)
const ResearcherDiscoverRoute = ResearcherDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ResearcherRoute,
} as any)
const ResearcherExpeditionsRoute = ResearcherExpeditionsRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => ResearcherRoute,
} as any)
const ResearcherResearchRoute = ResearcherResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ResearcherRoute,
} as any)
const ResearcherSavedRoute = ResearcherSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ResearcherRoute,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const UserAssistantRoute = UserAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => UserRoute,
} as any)
const UserExpeditionsRoute = UserExpeditionsRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => UserRoute,
} as any)
const UserMediaRoute = UserMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => UserRoute,
} as any)
const UserRepositoryRoute = UserRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => UserRoute,
} as any)
const UserSavedRoute = UserSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => UserRoute,
} as any)
const UserTimelineRoute = UserTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/researcher': typeof ResearcherRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/researcher/discover': typeof ResearcherDiscoverRoute
  '/researcher/expeditions': typeof ResearcherExpeditionsRoute
  '/researcher/research': typeof ResearcherResearchRoute
  '/researcher/saved': typeof ResearcherSavedRoute
  '/user/assistant': typeof UserAssistantRoute
  '/user/expeditions': typeof UserExpeditionsRoute
  '/user/media': typeof UserMediaRoute
  '/user/repository': typeof UserRepositoryRoute
  '/user/saved': typeof UserSavedRoute
  '/user/timeline': typeof UserTimelineRoute
  '/admin/': typeof AdminIndexRoute
  '/researcher/': typeof ResearcherIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/researcher/discover': typeof ResearcherDiscoverRoute
  '/researcher/expeditions': typeof ResearcherExpeditionsRoute
  '/researcher/research': typeof ResearcherResearchRoute
  '/researcher/saved': typeof ResearcherSavedRoute
  '/user/assistant': typeof UserAssistantRoute
  '/user/expeditions': typeof UserExpeditionsRoute
  '/user/media': typeof UserMediaRoute
  '/user/repository': typeof UserRepositoryRoute
  '/user/saved': typeof UserSavedRoute
  '/user/timeline': typeof UserTimelineRoute
  '/admin': typeof AdminIndexRoute
  '/researcher': typeof ResearcherIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/researcher': typeof ResearcherRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/researcher/discover': typeof ResearcherDiscoverRoute
  '/researcher/expeditions': typeof ResearcherExpeditionsRoute
  '/researcher/research': typeof ResearcherResearchRoute
  '/researcher/saved': typeof ResearcherSavedRoute
  '/user/assistant': typeof UserAssistantRoute
  '/user/expeditions': typeof UserExpeditionsRoute
  '/user/media': typeof UserMediaRoute
  '/user/repository': typeof UserRepositoryRoute
  '/user/saved': typeof UserSavedRoute
  '/user/timeline': typeof UserTimelineRoute
  '/admin/': typeof AdminIndexRoute
  '/researcher/': typeof ResearcherIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/researcher'
    | '/user'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/users'
    | '/researcher/discover'
    | '/researcher/expeditions'
    | '/researcher/research'
    | '/researcher/saved'
    | '/user/assistant'
    | '/user/expeditions'
    | '/user/media'
    | '/user/repository'
    | '/user/saved'
    | '/user/timeline'
    | '/admin/'
    | '/researcher/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/users'
    | '/researcher/discover'
    | '/researcher/expeditions'
    | '/researcher/research'
    | '/researcher/saved'
    | '/user/assistant'
    | '/user/expeditions'
    | '/user/media'
    | '/user/repository'
    | '/user/saved'
    | '/user/timeline'
    | '/admin'
    | '/researcher'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/researcher'
    | '/user'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/users'
    | '/researcher/discover'
    | '/researcher/expeditions'
    | '/researcher/research'
    | '/researcher/saved'
    | '/user/assistant'
    | '/user/expeditions'
    | '/user/media'
    | '/user/repository'
    | '/user/saved'
    | '/user/timeline'
    | '/admin/'
    | '/researcher/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResearcherRoute: typeof ResearcherRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researcher': {
      id: '/researcher'
      path: '/researcher'
      fullPath: '/researcher'
      preLoaderRoute: typeof ResearcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/researcher/': {
      id: '/researcher/'
      path: '/'
      fullPath: '/researcher/'
      preLoaderRoute: typeof ResearcherIndexRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/researcher/discover': {
      id: '/researcher/discover'
      path: '/discover'
      fullPath: '/researcher/discover'
      preLoaderRoute: typeof ResearcherDiscoverRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/researcher/expeditions': {
      id: '/researcher/expeditions'
      path: '/expeditions'
      fullPath: '/researcher/expeditions'
      preLoaderRoute: typeof ResearcherExpeditionsRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/researcher/research': {
      id: '/researcher/research'
      path: '/research'
      fullPath: '/researcher/research'
      preLoaderRoute: typeof ResearcherResearchRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/researcher/saved': {
      id: '/researcher/saved'
      path: '/saved'
      fullPath: '/researcher/saved'
      preLoaderRoute: typeof ResearcherSavedRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/assistant': {
      id: '/user/assistant'
      path: '/assistant'
      fullPath: '/user/assistant'
      preLoaderRoute: typeof UserAssistantRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/expeditions': {
      id: '/user/expeditions'
      path: '/expeditions'
      fullPath: '/user/expeditions'
      preLoaderRoute: typeof UserExpeditionsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/media': {
      id: '/user/media'
      path: '/media'
      fullPath: '/user/media'
      preLoaderRoute: typeof UserMediaRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/repository': {
      id: '/user/repository'
      path: '/repository'
      fullPath: '/user/repository'
      preLoaderRoute: typeof UserRepositoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/saved': {
      id: '/user/saved'
      path: '/saved'
      fullPath: '/user/saved'
      preLoaderRoute: typeof UserSavedRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/timeline': {
      id: '/user/timeline'
      path: '/timeline'
      fullPath: '/user/timeline'
      preLoaderRoute: typeof UserTimelineRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResearcherRouteChildren {
  ResearcherDiscoverRoute: typeof ResearcherDiscoverRoute
  ResearcherExpeditionsRoute: typeof ResearcherExpeditionsRoute
  ResearcherResearchRoute: typeof ResearcherResearchRoute
  ResearcherSavedRoute: typeof ResearcherSavedRoute
  ResearcherIndexRoute: typeof ResearcherIndexRoute
}

const ResearcherRouteChildren: ResearcherRouteChildren = {
  ResearcherDiscoverRoute: ResearcherDiscoverRoute,
  ResearcherExpeditionsRoute: ResearcherExpeditionsRoute,
  ResearcherResearchRoute: ResearcherResearchRoute,
  ResearcherSavedRoute: ResearcherSavedRoute,
  ResearcherIndexRoute: ResearcherIndexRoute,
}

const ResearcherRouteWithChildren = ResearcherRoute._addFileChildren(
  ResearcherRouteChildren,
)

interface UserRouteChildren {
  UserAssistantRoute: typeof UserAssistantRoute
  UserExpeditionsRoute: typeof UserExpeditionsRoute
  UserMediaRoute: typeof UserMediaRoute
  UserRepositoryRoute: typeof UserRepositoryRoute
  UserSavedRoute: typeof UserSavedRoute
  UserTimelineRoute: typeof UserTimelineRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAssistantRoute: UserAssistantRoute,
  UserExpeditionsRoute: UserExpeditionsRoute,
  UserMediaRoute: UserMediaRoute,
  UserRepositoryRoute: UserRepositoryRoute,
  UserSavedRoute: UserSavedRoute,
  UserTimelineRoute: UserTimelineRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ResearcherRoute: ResearcherRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
